# Generated by Django 5.0 on 2024-02-03 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('clubId', models.IntegerField(primary_key=True, serialize=False)),
                ('clubName', models.CharField(max_length=100)),
                ('clubImage', models.FileField(upload_to='club/static/assets')),
                ('clubDesc', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('clubLeader', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isLeader', models.BooleanField(default=False)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.clubs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=300)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.clubs')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.userid')),
            ],
        ),
    ]
