# Generated by Django 5.0 on 2024-01-13 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_clubs_clubdesc_clubs_clubimage_clubs_clubname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.clubs')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.userid')),
            ],
        ),
    ]
