# Generated by Django 5.0 on 2024-01-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_chats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='text',
            new_name='txt',
        ),
    ]
