# Generated by Django 5.0 on 2024-01-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_rename_text_chats_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='clubImage',
            field=models.FileField(upload_to='assets'),
        ),
    ]
