# Generated by Django 5.0 on 2024-01-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_clubs_clubimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='clubImage',
            field=models.FileField(upload_to='club/assets'),
        ),
    ]
