# Generated by Django 5.0 on 2024-01-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_alter_clubs_clubimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userid',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
